### ISSUE TITLE
断网缓存数据怎么加载的，或是怎么体现的？

### ISSUE THREAD

**Issue by MichealWangDan** [yale8848/RetrofitCache#10]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

**Comment by yale8848** [comment]
1.给接口添加如：@Cache(time = 200000)，先加载完一个接口，然后断网，在访问同一个接口，看能否正常显示数据；
2.看 LOGCAT TAG = retrofitcache 提示是否是从缓存加载的数据
