### ISSUE TITLE
@cache没加，断网还是加载缓存数据。

### ISSUE THREAD

**Issue by MichealWangDan** [yale8848/RetrofitCache#11]
登录接口断网是不希望走缓存的，但是断网还是读取缓存，怎么弄？
    @GET("center/inf4User/fakeLogin")
    Observable<ApiResponse<User>> login(@Query("username") String username, @Query("password") String password);

**Comment by yale8848** [comment]
你看看这个接口返回的header里是不是加缓存相关字段了？

**Comment by MichealWangDan** [comment]
Request Method:GET
Status Code:200 OK
Request Headers
Provisional headers are shown
Accept-Encoding:gzip
Connection:Keep-Alive
If-Modified-Since:Sat, 20 Jan 2018 05:53:50 GMT
User-Agent:okhttp/3.8.0
Query String Parametersview sourceview URL encoded
Response Headers
Content-Type:text/html;charset=UTF-8
Date:Mon, 22 Jan 2018 02:34:11 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked

哪些是的？怎么去除？

**Comment by yale8848** [comment]
哦 目前断网默认是直接从缓存拿数据的，如果你有断网不走缓存数据的需求的话，我下版本添加接口配置

**Comment by MichealWangDan** [comment]
可以，期待下个版本

**Comment by yale8848** [comment]
更新至1.0.6
forceCacheNoNet=false

**Comment by MichealWangDan** [comment]
好的，谢谢！
