### ISSUE TITLE
release版本不能获取mock数据么

### ISSUE THREAD

**Issue by q4452542007** [yale8848/RetrofitCache#29]
![image](https://user-images.githubusercontent.com/30925075/50428468-f9595580-08f2-11e9-9cdb-14ab3227d884.png)

实际的回调是空的  数据在哪里丢失了

**Comment by q4452542007** [comment]
debug版本一切正常

**Comment by yale8848** [comment]
混淆配置了吗？

**Comment by q4452542007** [comment]
配置了

**Comment by q4452542007** [comment]
是因为混淆导致变量名变了  所以解析不出来么

**Comment by q4452542007** [comment]
嗯  我看了下gson混淆文档  是这个问题造成的

**Comment by q4452542007** [comment]
问题已解决  感谢

**Comment by yale8848** [comment]
ok，没事
