### ISSUE TITLE
如何在下拉刷新的时候不走缓存.

### ISSUE THREAD

**Issue by hlgithub369** [yale8848/RetrofitCache#30]
Mobile:  

Android OS: 

NetWork: 

URL: 

LIB Version: 

---

大神你好.我知道可以在一定时间内请求一个接口后再次请求走的是缓存.
我想在用户下拉刷新的时候.去请求接口而不是请求缓存.请求完的接口后存为最新的缓存
有相应的方法吗?

**Comment by yale8848** [comment]
目前还没有这个方法，后续我想办法添加

**Comment by hlgithub369** [comment]
恩,谢谢!

**Comment by huanxinyanyue** [comment]
目前我想到的办法是强制清除缓存目录，但是这样很暴力，所有的http缓存都干掉了

**Comment by yale8848** [comment]
直接清除是很暴力的，你可以尝试先给url添加随机数使其成新的url，可以绕过缓存

**Comment by hlgithub369** [comment]
加随机数这个就很给力了.

**Comment by yale8848** [comment]
建议还是加个参数，在下拉刷新时把这参数值换成随机值，目前这个方法比较容易实现
