### ISSUE TITLE
rxjava2的库mock不了

### ISSUE THREAD

**Issue by GHChrisSu** [yale8848/RetrofitCache#33]
![image](https://user-images.githubusercontent.com/13779988/55617935-3e353800-57d0-11e9-873b-d384ec57c4e7.png)
![image](https://user-images.githubusercontent.com/13779988/55617985-5f962400-57d0-11e9-811e-958411f9a8cb.png)
获取不到Mock注解 rxjava2的library
作者请看一下

**Comment by yale8848** [comment]
收到，我看看

**Comment by yale8848** [comment]
麻烦把ApiRx2中的Mock改为；import ren.yale.android.retrofitcachelibrx2.anno.Mock;

**Comment by GHChrisSu** [comment]
可以了  谢谢  还有个issue想要添加协程的  要改coroutine的adapter  我看着貌似不能反射拿到。。。。。。。。     我目前是直接改adapter的代码的    还有okhttp的最新版本也变了  没有serviceMethod了  感觉可以从retrofit里面拿  但是改的多 没把握  我就先让工程用3.4的okhttp了

**Comment by yale8848** [comment]
高版本的okhttp我还没有研究过反射处理，如果没有serviceMethod，你可以看看其他变量，看能否通过反射处理。

**Comment by GHChrisSu** [comment]
OK  我先忙项目  后面有时间搞搞
