### ISSUE TITLE
Mock 与CacheForceInterceptorNoNet

### ISSUE THREAD

**Issue by protectedMan** [yale8848/RetrofitCache#37]
.addInterceptor(new CacheForceInterceptorNoNet())
如果不配置这一行，我注解的mock就不生效。

我主要是想用这个项目的注解式mock功能，不太需要缓存功能。

**Comment by yale8848** [comment]
目前mock功能在CacheForceInterceptorNoNet逻辑里，你可以不用 @Cache注解，只用@Mock注解就行了。

**Comment by protectedMan** [comment]
但是我如果配置这一行的话CacheForceInterceptorNoNet，断网时就会强制走缓存了啊，即使我没有配置cache。

**Comment by yale8848** [comment]
配置一下试试@Cache(forceCacheNoNet = false)

**Comment by protectedMan** [comment]
这个确实可以禁止缓存，那我所有接口都不需要配置缓存就要把WebService里面所有接口都需要加上这个注解了。

**Comment by yale8848** [comment]
嗯 你说的有道理，下个版本把这两个功能分离开

**Comment by protectedMan** [comment]
等一个新版本
![image](https://user-images.githubusercontent.com/17565737/61573441-5f9d0400-aae1-11e9-8380-34638b81e4fc.png)

**Comment by yale8848** [comment]
1.1.1 已经更新，你可以试试，clientBuilder.addInterceptor(new MockInterceptor());
