### ISSUE TITLE
缓存只支持get请求吗,post不支持吗

### ISSUE THREAD

**Issue by 900326** [yale8848/RetrofitCache#41]
我使用post请求,断网后,在缓存有效期内,不显示数据,是不支持post请求吗

https://github.com/z-chu/RxCache  
这个缓存库可以满足这个需求(有网络先加载缓存，再加载网络 #25),缓存策略也较全,但是使用麻烦,如果楼主可以结合他的缓存策略,保持你的库使用方式不变的情况就完美了,

**Comment by yale8848** [comment]
post理论上可以支持，但是不建议post缓存。
get通常是获取数据，我们缓存比较合理，post一般用于修改数据，不建议缓存数据。
谢谢你分享这个库，我后续再研究一下实现方式。

**Comment by 900326** [comment]
正常情况下是不需求post缓存的,有时候奇怪需求总是各种各样的,我公司的全部接口都是post,而我现在遇到的需求是,接口里面有些固定数据(或者一段时间内不变的数据,比如通过接口获取城市),对于这样的数据,我想做个缓存时间为一天或者一周,不论有网没网,只要有缓存就走缓存,超期后重新请求服务器,正常情况下正常返回服务器数据,如果此时更好服务器异常,就直接给用户显示服务器错误页面,谢谢你的回复,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yale"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午4:24
收件人:&nbsp;"yale8848/RetrofitCache"<RetrofitCache@noreply.github.com&gt;;
抄送:&nbsp;"似笑非笑"<895483316@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yale8848/RetrofitCache] 缓存只支持get请求吗,post不支持吗 (#41)




post理论上可以支持，但是不建议post缓存。
 get通常是获取数据，我们缓存比较合理，post一般用于修改数据，不建议缓存数据。
 谢谢你分享这个库，我后续再研究一下实现方式。
